bus_tracker-master/config/routes.rb
BusStop::Application.routes.draw do
  root :to => 'main#index'

  resources :lines

  resources :stations

  resources :main
end

bus_tracker-master/app/models/line.rb
class Line < ActiveRecord::Base
  validates :name, :presence => :true
  has_and_belongs_to_many :stations
end

bus_tracker-master/app/models/station.rb
class Station < ActiveRecord::Base
  validates :name, :presence => :true
  has_and_belongs_to_many :lines
end

bus_tracker-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception
end

bus_tracker-master/app/controllers/lines_controller.rb
class LinesController < ApplicationController
   def index
    @lines = Line.all
  end

  def new
    @line = Line.new
  end

  def create
    @line = Line.new(params[:name])
    if @line.save
      flash[:notice] = "line created"
      redirect_to lines_path
    else
      render 'new'
    end
  end

  def edit
    @line = Line.find(params[:id])
  end

  def update
    @line = Line.find(params[:id])
    if @line.update(params[:name])
      flash[:notice] = "line updated!"
      redirect_to lines_path(@line)
    else
      render 'edit'
    end
  end

  def destroy
    @line = Line.find(params[:id])
    @line.destroy
    flash[:notice] = "line delete."
    redirect_to lines_path
  end
end

bus_tracker-master/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index

  end
end

bus_tracker-master/app/controllers/stations_controller.rb
class StationsController < ApplicationController
  def index
    @stations = Station.all
  end

  def new
    @station = Station.new
  end

  def create
    @station = Station.new(station_params)
    if @station.save
      flash[:notice] = "Station created"
      redirect_to stations_path
    else
      render 'new'
    end
  end

  def show
    @station = Station.find(params[:id])
    render :stations
  end

  def edit
    @station = Station.find(params[:id])
  end

  def update
    @station = Station.find(params[:id])
    if @station.update(params[:name])
      flash[:notice] = "Station updated!"
      redirect_to stations_path(@station)
    else
      render 'edit'
    end
  end

  def destroy
    @station = Station.find(params[:id])
    @station.destroy
    flash[:notice] = "Station delete."
    redirect_to stations_path
  end

private

  def station_params
    params.require(:station).permit(:name)
  end

end

bus_tracker-master/app/helpers/application_helper.rb
module ApplicationHelper
end

bus_tracker-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BusStop</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= flash[:alert] %>
<%= flash[:notice] %>

<%= yield %>

</body>
</html>

bus_tracker-master/app/views/main/index.html.erb
<h1>Welcome To Bus Finder</h1>

<h2>Add Stations and Lines</h2>
<%= link_to "New Station", new_station_path, :class=> "btn btn-default" %>
<%= link_to "New Line", new_line_path, :class=> "btn btn-default" %>

<h2>View Stations and Lines</h2>
<%= link_to "View Stations", stations_path, :class=> "btn btn-default" %>
<%= link_to "View Lines", lines_path, :class=> "btn btn-default" %>