grouptextapp-master/config/routes.rb
Textapp::Application.routes.draw do
  devise_for :users

  resources :messages, :only => [:index, :new, :create, :show]
  root to: 'messages#home'

end

grouptextapp-master/app/models/message.rb
class Message < ActiveRecord::Base
  before_create :send_message

private

  def send_message
    response = RestClient::Request.new(
      :method => :post,
      :url => 'https://api.twilio.com/2010-04-01/Accounts/ACd1c0ca750bf3056c0fa69f3d18e67e0a/Messages.json',
      :user => ENV['TWILIO_ACCOUNT_SID'],
      :password => ENV['TWILIO_AUTH_TOKEN'],
      :payload => { :Body => body,
                    :To => to,
                    :From => from }
  ).execute
  end
end

grouptextapp-master/app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

grouptextapp-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private

  def user_params
    params.require(:user).permit(:email,
                                 :password,
                                 :password_confirmation,
                                 :remember_me)
  end


end

grouptextapp-master/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      flash[:notice] = "Your message was sent!"
      redirect_to messages_path
    else
      render
    end
  end

  def show
    @message = Message.find(params[:id])
  end

private

  def message_params
    params.require(:message).permit(:to, :from, :body)
  end
end

grouptextapp-master/app/helpers/application_helper.rb
module ApplicationHelper
end

grouptextapp-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Textapp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <div id="container">
      <div id="user_nav">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete %> |
           <%= link_to "Send a message", new_message_path %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path %> |
          <%= link_to "Login", new_user_session_path %>
        <% end %>
      </div>

      <%= flash[:notice] %>
      <%= yield %>
    </div>
  </div>


</body>
</html>