link-board-master/hackernewsclone/config/routes.rb
Hackernewsclone::Application.routes.draw do
  resources :links
  resources :users
end

link-board-master/hackernewsclone/app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, presence: true
  validates :user_id, presence: true
  validates :commentable_id, presence: true
  validates :commentable_type, presence: true
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
end

link-board-master/hackernewsclone/app/models/link.rb
class Link < ActiveRecord::Base
  validates :title, presence: true, uniqueness: true
  validates :url, presence: true
  validates :post_date, presence: true
  belongs_to :user
  has_many :comments, as: :commentable
end

link-board-master/hackernewsclone/app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true, uniqueness: true
  has_many :links
  has_many :comments
end

link-board-master/hackernewsclone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

link-board-master/hackernewsclone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

link-board-master/hackernewsclone/app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render action: 'show', status: :created, location: @link }
      else
        format.html { render action: 'new' }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url, :post_date, :user_id)
    end
end

link-board-master/hackernewsclone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
    render 'new'
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'User created.'
      redirect_to users_path
    else
      render 'new'
    end
  end



private
  def user_params
    params.require(:user).permit(:username)
  end
end

link-board-master/hackernewsclone/app/helpers/application_helper.rb
module ApplicationHelper
end

link-board-master/hackernewsclone/app/helpers/links_helper.rb
module LinksHelper
end

link-board-master/hackernewsclone/app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :post_date %><br>
    <%= f.datetime_select :post_date %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

link-board-master/hackernewsclone/app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

link-board-master/hackernewsclone/app/views/links/index.html.erb
<h1>Listing links</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Post date</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.title %></td>
        <td><%= link.url %></td>
        <td><%= link.post_date %></td>
        <td><%= link.user_id %></td>
        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Delete', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

link-board-master/hackernewsclone/app/views/links/new.html.erb
<h1>New link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

link-board-master/hackernewsclone/app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @link.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @link.url %>
</p>

<p>
  <strong>Post date:</strong>
  <%= @link.post_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @link.user_id %>
</p>

<form>
  <input type='text' name='comment'>
</form>

<% if @link.comments.any? %>
  <div class="row">
    <% @link.comments.each do |comment| %>
      <%= render('comments/comments', comment: comment) %>
    <% end %>
  </div>
<% end %>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>